Models/Batch.cs
using System;

namespace Bakery.Models
{
    public class Batch
    {
        public Guid Id {get;set;}
        public Guid InventoryItemId {get;set;}
        public int Quantity {get;set;}
        public int RemainingQuantity {get;set;}
        public bool IsArchived {get;set;}
        public DateTime ProductionDate {get;set;}

        public Guid UserId { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Bakery.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/InventoryItem.cs
using System;
using System.Collections.Generic;

namespace Bakery.Models
{
    public class InventoryItem
    {
        public Guid Id {get;set;}
        public string Name {get;set;}
        public string Description {get;set;}
        public decimal Price {get;set;}
        public int DaysToSell {get;set;}
        public bool IsDeleted {get;set;}
        public List<Batch> Batches {get;set;}

        public Guid UserId { get; set; }
    }
}

Controllers/BatchController.cs
using System;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Bakery.Models;
using Bakery.DAL;

namespace Bakery.Controllers
{
    public class BatchController : Controller
    {
        private readonly ILogger<BatchController> _logger;
        private IStoreBatches _batchStorage;

        public BatchController(ILogger<BatchController> logger, IStoreBatches batchStorage)
        {
            _logger = logger;
            _batchStorage = batchStorage;
        }

        public IActionResult Create(Guid inventoryItemId)
        {
            var batch = new Batch();
            batch.InventoryItemId = inventoryItemId;
            return View(batch);
        }

        [HttpPost]
        public IActionResult Create(Batch newBatch , Guid userid)
        {
            newBatch.RemainingQuantity = newBatch.Quantity;
            _batchStorage.AddBatch(newBatch, userid);
            return RedirectToAction("Details", "Inventory", new { id = newBatch.InventoryItemId});
        }

        public IActionResult Update(Guid inventoryItemId, Guid batchId , Guid userid)
        {
            var batch = _batchStorage.GetBatch(inventoryItemId, batchId , userid);
            return View(batch);
        }

        [HttpPost]
        public IActionResult Update(Batch updatedBatch , Guid userid)
        {
            _batchStorage.UpdateBatch(updatedBatch , userid);
            return RedirectToAction("Details", "Inventory", new { id = updatedBatch.InventoryItemId});
        }

        [HttpPost]
        public IActionResult Delete(Guid inventoryItemId, Guid Id, Guid userid) {
            _batchStorage.DeleteBatch(inventoryItemId, Id, userid);
            return RedirectToAction("Details", "Inventory", new { id = inventoryItemId});
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Bakery.Models;
using Bakery.DAL;

namespace Bakery.Controllers
{
    public class InventoryController : Controller
    {
        private IStoreInventoryItems _inventoryStorage;

        public InventoryController(IStoreInventoryItems inventoryStorage)
        {
            _inventoryStorage = inventoryStorage;
        }

        public IActionResult Index(Guid userid) {
            var result = _inventoryStorage.GetAll(userid);
            return View(result);
        }

        public IActionResult Details(Guid id , Guid userid) {
            var item = _inventoryStorage.GetById(id , userid);
            return View(item);
        }

        public IActionResult Create() {
            return View("Upsert");
        }

        [HttpPost]
        public IActionResult Create(InventoryItem newItem) {
            newItem.Id = Guid.NewGuid();
            newItem.Batches = new List<Batch>();
            _inventoryStorage.Create(newItem);
            return RedirectToAction("Index");
        }

        public IActionResult Update(Guid id, Guid userid ) {
            ViewBag.IsEditing = true;
            var item = _inventoryStorage.GetById(id , userid);
            return View("Upsert", item);
        }

        [HttpPost]
        public IActionResult Update(InventoryItem updatedItem) {
            _inventoryStorage.Update(updatedItem);
            return RedirectToAction("Details", "Inventory", new { id = updatedItem.Id});
        }

        [HttpPost]
        public IActionResult Delete(Guid id , Guid userid) {
            _inventoryStorage.Delete(id , userid);
            return RedirectToAction("Index");
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Batch/Create.cshtml
@model Batch

<div>
    <div>
        <h3 style="display:inline">New Batch</h1>
        <a asp-controller="Inventory" asp-action="Details" asp-route-id="@Model.InventoryItemId" class="btn btn-primary" style="float:right">Back to Item</a>
    </div>
    <hr/>

    <form asp-action="Create">
        <input type="hidden" asp-for="InventoryItemId"/>
        <div class="form-group">
            <label asp-for="Quantity">Quantity</label>
            <input type="text" class="form-control" asp-for="Quantity"/>
        </div>
        <div class="form-group">
            <label asp-for="ProductionDate">Date</label>
            <input type="date" value="@DateTime.Now.ToString("yyyy-MM-dd")" class="form-control" asp-for="ProductionDate"/>
        </div>
        <button class="btn btn-success" type="submit">Add</button>
    </form>
</div>

Views/Batch/Update.cshtml
@model Batch

<div>
    <div>
        <h3 style="display:inline">Update Batch</h1>
        <a asp-controller="Inventory" asp-action="Details" asp-route-id="@Model.InventoryItemId" class="btn btn-primary" style="float:right">Back to Item</a>
    </div>
    <hr/>

    <form asp-action="Update">
        <input type="hidden" asp-for="Id"/>
        <input type="hidden" asp-for="InventoryItemId"/>
        <input type="hidden" asp-for="ProductionDate"/>
        <input type="hidden" asp-for="Quantity"/>  
        <div class="form-group">
            <label asp-for="Quantity">Remaining Quantity</label>
            <input type="number" min="0" max="@Model.Quantity" class="form-control" asp-for="RemainingQuantity"/>
        </div>
        <div class="form-group">
            <label asp-for="Quantity">Quantity</label>
            <span class="form-control">@Model.Quantity</span>
        </div>
        <div class="form-group">
            <label asp-for="ProductionDate">Date</label>
            <span class="form-control">@Model.ProductionDate.ToString("yyyy-MM-dd")</span>
        </div>
        <button class="btn btn-success" type="submit">Update</button>
    </form>
    <hr/>
    @if (Model.RemainingQuantity == 0) {     
        <form asp-action="Delete">
            <input type="hidden" asp-for="InventoryItemId"/>
            <input type="hidden" asp-for="Id"/>
            <button type="submit" class="btn btn-primary">Archive</button>
        </form>
    }
</div>

Views/Inventory/Details.cshtml
@model InventoryItem
@{
    var batches = Model.Batches.Where(x => x.IsArchived == false);
}

<div>
    <div>
        <h3 style="display:inline">Item Details</h1>
        <a asp-action="Index" class="btn btn-primary" style="float:right">Back</a>
    </div>
    <hr/>
    <div class="row">
        <div class="col-md-5">
            <dl class="row">
                <dt class="col-sm-4">Name</dt>
                <dd class="col-sm-8">@Model.Name</dd>

                <dt class="col-sm-4">Description</dt>
                <dd class="col-sm-8">@Model.Description</dd>

                <dt class="col-sm-4">Price</dt>
                <dd class="col-sm-8">@Model.Price</dd>

                <dt class="col-sm-4">Days to Sell</dt>
                <dd class="col-sm-8">@Model.DaysToSell</dd>

                <dt class="col-sm-4">Remaining Quantity</dt>
                <dd class="col-sm-8">@Model.Batches.Sum(x => x.RemainingQuantity)</dd>
                
            </dl>
            <br/>
            <a asp-action="Update" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
            <form asp-action="Delete" style="display:inline">
                <input type="hidden" asp-for="Id"/>
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
            <a asp-controller="Batch" asp-action="Create" asp-route-InventoryItemId="@Model.Id" class="btn btn-success">New Batch</a>
        </div>
        <div class="col-md-7">
            <div>
            @if (batches.Count() == 0) {
                <div>No batches made</div>
            } else {
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Production Date</th>
                            <th>Remaining</th>
                            <th>Initial</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var batch in batches) {
                            var rowClass = "";
                            if ((DateTime.Now - batch.ProductionDate).TotalDays + 1 > Model.DaysToSell){
                                rowClass="table-warning";
                            }
                            if ((DateTime.Now - batch.ProductionDate).TotalDays > Model.DaysToSell){
                                rowClass="table-danger";
                            }
                            if (batch.RemainingQuantity == 0) {
                                rowClass = "table-secondary";
                            }
                        <tr class="@rowClass">
                            <td>@batch.ProductionDate</td>
                            <td>@batch.RemainingQuantity</td>
                            <td>@batch.Quantity</td>
                            <td>
                                <a asp-controller="Batch" asp-action="Update" asp-route-inventoryItemId="@batch.InventoryItemId" asp-route-batchId="@batch.Id">Update</a>
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            }
            </div>
        </div>
    </div>
</div>

Views/Inventory/Index.cshtml
@model List<InventoryItem>

<div>
    <div>
        <h3 style="display:inline">Inventory</h3>
        <a asp-action="Create" class="btn btn-primary" style="float:right">New Item</a>
    </div>
    <hr/>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Price</th>
                <th>Quantity</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>@item.Name</td>
                <td>@item.Description</td>
                <td>@item.Price</td>
                <td>@item.Batches.Sum(x => x.RemainingQuantity)</td>
                <td><a asp-action="Details" asp-route-id="@item.Id">Details</a></td>
            </tr>
        }
        </tbody>
    </table>
</div>

Views/Inventory/Upsert.cshtml
@model InventoryItem

@{
    var action = "Create";
    var buttonText = "Create";
    var title = "New Inventory Item";

    if (ViewBag.IsEditing == true) {
        action = "Update";
        buttonText = "Update";
        title = "Update Inventory Item";
    }
}
<div>
    <div>
        <h3 style="display:inline">@title</h1>
        <a asp-action="Index" class="btn btn-primary" style="float:right">Back</a>
    </div>
    <hr/>
    
    <form asp-action="@action">
        <input type="hidden" asp-for="Id"/>
        <div class="form-group">
            <label asp-for="Name">Name</label>
            <input type="text" class="form-control" asp-for="Name"/>
        </div>
        <div class="form-group">
            <label asp-for="Description">Description</label>
            <input type="text" class="form-control" asp-for="Description"/>
        </div>
        <div class="form-group">
            <label asp-for="Price">Price</label>
            <input type="text" class="form-control" asp-for="Price"/>
        </div>
        <div class="form-group">
            <label asp-for="Price">Days to Sell</label>
            <input type="number" class="form-control" asp-for="DaysToSell"/>
        </div>
        <button class="btn btn-success" type="submit">@buttonText</button>
    </form>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bakery</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Inventory" asp-action="Index">Bakery</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ComitBakery - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>